# Generated by Django 4.0.2 on 2022-03-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_item_id_alter_monster_id_alter_room_id_and_more'),
        ('website', '0003_user_last_join_time'),
    ]

    operations = [
    ]
