# Generated by Django 2.1.5 on 2022-03-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
