# Generated by Django 2.1.5 on 2022-03-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220313_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
