# Generated by Django 2.1.5 on 2022-03-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20220315_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
