# Generated by Django 2.1.5 on 2022-03-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_monster_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='index',
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
